/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AttachmentsRouteImport } from './routes/attachments'
import { Route as BudgetsRouteImport } from './routes/budgets'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts_.$accountId'
import { Route as ApiProxySplatRouteImport } from './routes/api-proxy.$'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as CardsCardIdRouteImport } from './routes/cards_.$cardId'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories_.$categoryId'
import { Route as PeoplePersonIdRouteImport } from './routes/people_.$personId'
import { Route as PersonConnectionsAcceptRouteImport } from './routes/person-connections.accept'
import { Route as ReportsCategoryTrendsRouteImport } from './routes/reports/category-trends'
import { Route as ReportsInstallmentsRouteImport } from './routes/reports/installments'
import { Route as ReportsRecurringExpensesRouteImport } from './routes/reports/recurring-expenses'
import { Route as TransactionsImportRouteImport } from './routes/transactions_.import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AttachmentsRoute = AttachmentsRouteImport.update({
  id: '/attachments',
  path: '/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetsRoute = BudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/accounts_/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api-proxy/$',
  path: '/api-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards_/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories_/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people_/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonConnectionsAcceptRoute = PersonConnectionsAcceptRouteImport.update({
  id: '/person-connections/accept',
  path: '/person-connections/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCategoryTrendsRoute = ReportsCategoryTrendsRouteImport.update({
  id: '/reports/category-trends',
  path: '/reports/category-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInstallmentsRoute = ReportsInstallmentsRouteImport.update({
  id: '/reports/installments',
  path: '/reports/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRecurringExpensesRoute =
  ReportsRecurringExpensesRouteImport.update({
    id: '/reports/recurring-expenses',
    path: '/reports/recurring-expenses',
    getParentRoute: () => rootRouteImport,
  } as any)
const TransactionsImportRoute = TransactionsImportRouteImport.update({
  id: '/transactions_/import',
  path: '/transactions/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/attachments': typeof AttachmentsRoute
  '/budgets': typeof BudgetsRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/notes': typeof NotesRoute
  '/people': typeof PeopleRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/api-proxy/$': typeof ApiProxySplatRoute
  '/api/$': typeof ApiSplatRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/person-connections/accept': typeof PersonConnectionsAcceptRoute
  '/reports/category-trends': typeof ReportsCategoryTrendsRoute
  '/reports/installments': typeof ReportsInstallmentsRoute
  '/reports/recurring-expenses': typeof ReportsRecurringExpensesRoute
  '/transactions/import': typeof TransactionsImportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/attachments': typeof AttachmentsRoute
  '/budgets': typeof BudgetsRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/notes': typeof NotesRoute
  '/people': typeof PeopleRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/api-proxy/$': typeof ApiProxySplatRoute
  '/api/$': typeof ApiSplatRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/person-connections/accept': typeof PersonConnectionsAcceptRoute
  '/reports/category-trends': typeof ReportsCategoryTrendsRoute
  '/reports/installments': typeof ReportsInstallmentsRoute
  '/reports/recurring-expenses': typeof ReportsRecurringExpensesRoute
  '/transactions/import': typeof TransactionsImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/attachments': typeof AttachmentsRoute
  '/budgets': typeof BudgetsRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/changelog': typeof ChangelogRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/notes': typeof NotesRoute
  '/people': typeof PeopleRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/accounts_/$accountId': typeof AccountsAccountIdRoute
  '/api-proxy/$': typeof ApiProxySplatRoute
  '/api/$': typeof ApiSplatRoute
  '/cards_/$cardId': typeof CardsCardIdRoute
  '/categories_/$categoryId': typeof CategoriesCategoryIdRoute
  '/people_/$personId': typeof PeoplePersonIdRoute
  '/person-connections/accept': typeof PersonConnectionsAcceptRoute
  '/reports/category-trends': typeof ReportsCategoryTrendsRoute
  '/reports/installments': typeof ReportsInstallmentsRoute
  '/reports/recurring-expenses': typeof ReportsRecurringExpensesRoute
  '/transactions_/import': typeof TransactionsImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/attachments'
    | '/budgets'
    | '/cards'
    | '/categories'
    | '/changelog'
    | '/dashboard'
    | '/inbox'
    | '/notes'
    | '/people'
    | '/robots.txt'
    | '/settings'
    | '/signup'
    | '/transactions'
    | '/accounts/$accountId'
    | '/api-proxy/$'
    | '/api/$'
    | '/cards/$cardId'
    | '/categories/$categoryId'
    | '/people/$personId'
    | '/person-connections/accept'
    | '/reports/category-trends'
    | '/reports/installments'
    | '/reports/recurring-expenses'
    | '/transactions/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/attachments'
    | '/budgets'
    | '/cards'
    | '/categories'
    | '/changelog'
    | '/dashboard'
    | '/inbox'
    | '/notes'
    | '/people'
    | '/robots.txt'
    | '/settings'
    | '/signup'
    | '/transactions'
    | '/accounts/$accountId'
    | '/api-proxy/$'
    | '/api/$'
    | '/cards/$cardId'
    | '/categories/$categoryId'
    | '/people/$personId'
    | '/person-connections/accept'
    | '/reports/category-trends'
    | '/reports/installments'
    | '/reports/recurring-expenses'
    | '/transactions/import'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/attachments'
    | '/budgets'
    | '/cards'
    | '/categories'
    | '/changelog'
    | '/dashboard'
    | '/inbox'
    | '/notes'
    | '/people'
    | '/robots.txt'
    | '/settings'
    | '/signup'
    | '/transactions'
    | '/accounts_/$accountId'
    | '/api-proxy/$'
    | '/api/$'
    | '/cards_/$cardId'
    | '/categories_/$categoryId'
    | '/people_/$personId'
    | '/person-connections/accept'
    | '/reports/category-trends'
    | '/reports/installments'
    | '/reports/recurring-expenses'
    | '/transactions_/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AttachmentsRoute: typeof AttachmentsRoute
  BudgetsRoute: typeof BudgetsRoute
  CardsRoute: typeof CardsRoute
  CategoriesRoute: typeof CategoriesRoute
  ChangelogRoute: typeof ChangelogRoute
  DashboardRoute: typeof DashboardRoute
  InboxRoute: typeof InboxRoute
  NotesRoute: typeof NotesRoute
  PeopleRoute: typeof PeopleRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TransactionsRoute: typeof TransactionsRoute
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  PersonConnectionsAcceptRoute: typeof PersonConnectionsAcceptRoute
  ReportsCategoryTrendsRoute: typeof ReportsCategoryTrendsRoute
  ReportsInstallmentsRoute: typeof ReportsInstallmentsRoute
  ReportsRecurringExpensesRoute: typeof ReportsRecurringExpensesRoute
  TransactionsImportRoute: typeof TransactionsImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attachments': {
      id: '/attachments'
      path: '/attachments'
      fullPath: '/attachments'
      preLoaderRoute: typeof AttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budgets': {
      id: '/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof BudgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts_/$accountId': {
      id: '/accounts_/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-proxy/$': {
      id: '/api-proxy/$'
      path: '/api-proxy/$'
      fullPath: '/api-proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards_/$cardId': {
      id: '/cards_/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories_/$categoryId': {
      id: '/categories_/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people_/$personId': {
      id: '/people_/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person-connections/accept': {
      id: '/person-connections/accept'
      path: '/person-connections/accept'
      fullPath: '/person-connections/accept'
      preLoaderRoute: typeof PersonConnectionsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/category-trends': {
      id: '/reports/category-trends'
      path: '/reports/category-trends'
      fullPath: '/reports/category-trends'
      preLoaderRoute: typeof ReportsCategoryTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/installments': {
      id: '/reports/installments'
      path: '/reports/installments'
      fullPath: '/reports/installments'
      preLoaderRoute: typeof ReportsInstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/recurring-expenses': {
      id: '/reports/recurring-expenses'
      path: '/reports/recurring-expenses'
      fullPath: '/reports/recurring-expenses'
      preLoaderRoute: typeof ReportsRecurringExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions_/import': {
      id: '/transactions_/import'
      path: '/transactions/import'
      fullPath: '/transactions/import'
      preLoaderRoute: typeof TransactionsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AttachmentsRoute: AttachmentsRoute,
  BudgetsRoute: BudgetsRoute,
  CardsRoute: CardsRoute,
  CategoriesRoute: CategoriesRoute,
  ChangelogRoute: ChangelogRoute,
  DashboardRoute: DashboardRoute,
  InboxRoute: InboxRoute,
  NotesRoute: NotesRoute,
  PeopleRoute: PeopleRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TransactionsRoute: TransactionsRoute,
  AccountsAccountIdRoute: AccountsAccountIdRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  PersonConnectionsAcceptRoute: PersonConnectionsAcceptRoute,
  ReportsCategoryTrendsRoute: ReportsCategoryTrendsRoute,
  ReportsInstallmentsRoute: ReportsInstallmentsRoute,
  ReportsRecurringExpensesRoute: ReportsRecurringExpensesRoute,
  TransactionsImportRoute: TransactionsImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
