import {
  ArrowLeftRight,
  Baby,
  BadgeDollarSign,
  Beer,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Bus,
  CalendarDays,
  Camera,
  Car,
  ChartNoAxesCombined,
  CircleDollarSign,
  Clock3,
  Cloud,
  Coffee,
  Compass,
  CreditCard,
  Download,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  Globe2,
  GraduationCap,
  HandCoins,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  Hourglass,
  KeyRound,
  Landmark,
  Leaf,
  Lightbulb,
  Link,
  LockKeyhole,
  type LucideIcon,
  MapPin,
  Medal,
  Mic2,
  Monitor,
  Moon,
  MoreHorizontal,
  Mouse,
  Music2,
  Paperclip,
  PawPrint,
  Pencil,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  Scale,
  School,
  Settings,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Ticket,
  Timer,
  Train,
  TreePine,
  TrendingUp,
  Trophy,
  Umbrella,
  Upload,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";
import { cn } from "@/lib/utils";

const option = (value: string, label: string, icon: LucideIcon) => ({ value, label, icon });

export const categoryIconOptions = [
  option("circle-dollar-sign", "Dinheiro", CircleDollarSign),
  option("wallet", "Carteira", Wallet),
  option("credit-card", "Cartão", CreditCard),
  option("landmark", "Banco", Landmark),
  option("hand-coins", "Moedas", HandCoins),
  option("chart", "Gráfico", ChartNoAxesCombined),
  option("trending-up", "Rendimentos", TrendingUp),
  option("refresh-cw", "Reembolso", RefreshCw),
  option("badge-dollar-sign", "Pagamento", BadgeDollarSign),
  option("shopping-cart", "Carrinho", ShoppingCart),
  option("shopping-bag", "Sacola", ShoppingBag),
  option("shopping-basket", "Cesta", ShoppingBasket),
  option("store", "Loja", Store),
  option("gift", "Presente", Gift),
  option("ticket", "Ticket", Ticket),
  option("utensils", "Alimentação", Utensils),
  option("restaurant", "Restaurante", UtensilsCrossed),
  option("coffee", "Café", Coffee),
  option("pizza", "Pizza", Pizza),
  option("beer", "Bebida", Beer),
  option("car", "Carro", Car),
  option("bus", "Ônibus", Bus),
  option("bike", "Bicicleta", Bike),
  option("train", "Trem", Train),
  option("plane", "Avião", Plane),
  option("map-pin", "Localização", MapPin),
  option("fuel", "Combustível", Fuel),
  option("home", "Casa", Home),
  option("building", "Prédio", Building2),
  option("wrench", "Ferramentas", Wrench),
  option("lightbulb", "Lâmpada", Lightbulb),
  option("zap", "Energia", Zap),
  option("droplets", "Água", Droplets),
  option("heart-pulse", "Saúde", HeartPulse),
  option("hospital", "Hospital", Hospital),
  option("heart", "Coração", Heart),
  option("pill", "Farmácia", Pill),
  option("dumbbell", "Fitness", Dumbbell),
  option("book-open", "Livro", BookOpen),
  option("graduation-cap", "Graduação", GraduationCap),
  option("school", "Escola", School),
  option("pencil", "Lápis", Pencil),
  option("briefcase", "Trabalho", BriefcaseBusiness),
  option("gamepad", "Jogos", Gamepad2),
  option("film", "Filme", Film),
  option("music", "Música", Music2),
  option("mic", "Microfone", Mic2),
  option("headphones", "Fone", Headphones),
  option("camera", "Câmera", Camera),
  option("umbrella", "Praia", Umbrella),
  option("wifi", "Wi-Fi", Wifi),
  option("smartphone", "Celular", Smartphone),
  option("monitor", "Computador", Monitor),
  option("mouse", "Mouse", Mouse),
  option("user", "Pessoa", User),
  option("users", "Família", Users),
  option("baby", "Bebê", Baby),
  option("paw-print", "Pets", PawPrint),
  option("shirt", "Vestuário", Shirt),
  option("file-text", "Documento", FileText),
  option("receipt", "Conta", Receipt),
  option("scale", "Balança", Scale),
  option("shield-check", "Proteção", ShieldCheck),
  option("repeat", "Assinatura", Repeat),
  option("medal", "Prêmio", Medal),
  option("trophy", "Troféu", Trophy),
  option("star", "Estrela", Star),
  option("rocket", "Foguete", Rocket),
  option("hourglass", "Ampulheta", Hourglass),
  option("calendar", "Calendário", CalendarDays),
  option("clock", "Relógio", Clock3),
  option("timer", "Timer", Timer),
  option("flame", "Fogo", Flame),
  option("sun", "Sol", Sun),
  option("moon", "Lua", Moon),
  option("cloud", "Nuvem", Cloud),
  option("leaf", "Planta", Leaf),
  option("tree", "Árvore", TreePine),
  option("globe", "Globo", Globe2),
  option("compass", "Bússola", Compass),
  option("recycle", "Reciclagem", Recycle),
  option("lock", "Cadeado", LockKeyhole),
  option("key", "Chave", KeyRound),
  option("settings", "Configurações", Settings),
  option("link", "Link", Link),
  option("paperclip", "Anexo", Paperclip),
  option("download", "Download", Download),
  option("upload", "Upload", Upload),
  option("arrow-left-right", "Transferência", ArrowLeftRight),
  option("sparkles", "Outros", Sparkles),
  option("tag", "Categoria", Tag),
  option("more-horizontal", "Mais", MoreHorizontal),
] as const;

export function CategoryIcon({ className, name }: { className?: string; name?: string | null }) {
  const Icon = categoryIconOptions.find((item) => item.value === name)?.icon ?? Tag;
  return <Icon aria-hidden="true" className={cn("size-5", className)} />;
}
