const logoLabels: Record<string, string> = {
  "/logos/99Pay.png": "99Pay",
  "/logos/abnamro.png": "ABN AMRO",
  "/logos/agbank.png": "AgBank",
  "/logos/agibank.png": "Agibank",
  "/logos/agora.png": "Agora",
  "/logos/alelo.png": "Alelo",
  "/logos/amex.png": "American Express",
  "/logos/azul.png": "Azul",
  "/logos/b3.png": "B3",
  "/logos/bancopatagonia.png": "Banco Patagonia",
  "/logos/banrisul.png": "Banrisul",
  "/logos/bb.png": "Banco do Brasil",
  "/logos/bemol.png": "Bemol",
  "/logos/binance.png": "Binance",
  "/logos/bmg.png": "BMG",
  "/logos/bradesco-prime.png": "Bradesco Prime",
  "/logos/bradesco.png": "Bradesco",
  "/logos/brb.png": "BRB",
  "/logos/bs2.png": "BS2",
  "/logos/btg.empresas.png": "BTG Empresas",
  "/logos/bv.png": "BV",
  "/logos/c-a.png": "C&A",
  "/logos/c6bank.png": "C6 Bank",
  "/logos/caixa.png": "Caixa",
  "/logos/caju.png": "Caju",
  "/logos/carrefour.png": "Carrefour",
  "/logos/cetelem.png": "Cetelem",
  "/logos/citibank.png": "Citibank",
  "/logos/coinbase.png": "Coinbase",
  "/logos/contasimples.png": "Conta Simples",
  "/logos/cooperativa-ailos.png": "Cooperativa Ailos",
  "/logos/cooperativa-cresol.png": "Cooperativa Cresol",
  "/logos/coopercard.png": "Coopercard",
  "/logos/credicard-on.png": "Credicard On",
  "/logos/credicard-zero.png": "Credicard Zero",
  "/logos/credicard.png": "Credicard",
  "/logos/creditas.png": "Creditas",
  "/logos/credito.agricola.png": "Credito Agricola",
  "/logos/creditoemiliano.png": "Credito Emiliano",
  "/logos/crefisa.png": "Crefisa",
  "/logos/cruzeirodosul.png": "Cruzeiro do Sul",
  "/logos/crypto-com.png": "Crypto.com",
  "/logos/digio.png": "Digio",
  "/logos/digiplus.png": "Digi+",
  "/logos/diners.png": "Diners Club",
  "/logos/dinheiro.png": "Dinheiro",
  "/logos/dotz.png": "Dotz",
  "/logos/easynvest.png": "Easynvest",
  "/logos/elo.png": "Elo",
  "/logos/eqi.png": "EQI",
  "/logos/flash.png": "Flash",
  "/logos/foxbit.png": "Foxbit",
  "/logos/genial.png": "Genial",
  "/logos/grao.png": "Grao",
  "/logos/havan.png": "Havan",
  "/logos/hipercard.png": "Hipercard",
  "/logos/hotmart.png": "Hotmart",
  "/logos/hsbc.png": "HSBC",
  "/logos/ifood-conta-digital.png": "iFood Conta Digital",
  "/logos/infinitepay.png": "InfinitePay",
  "/logos/intermedium.png": "Inter",
  "/logos/interpj.png": "Inter PJ",
  "/logos/iob-beneficio.png": "IOB Benefício",
  "/logos/ion.png": "Ion",
  "/logos/itau-uniclass.png": "Itaú Uniclass",
  "/logos/itau.png": "Itaú",
  "/logos/itaupersonnalite.png": "Itaú Personnalite",
  "/logos/iti.png": "Iti",
  "/logos/latam.pass.png": "LATAM Pass",
  "/logos/lojasamericanas.png": "Lojas Americanas",
  "/logos/magalu-pay.png": "MagaluPay",
  "/logos/marisa.png": "Marisa",
  "/logos/master-black.png": "Mastercard Black",
  "/logos/mastercard.png": "Mastercard",
  "/logos/meliuz.png": "Meliuz",
  "/logos/mercadobitcoin.png": "Mercado Bitcoin",
  "/logos/mercadolivre.png": "Mercado Livre",
  "/logos/mercadopago.png": "Mercado Pago",
  "/logos/mercadopagocartao.png": "Mercado Pago Cartão",
  "/logos/midway.png": "Midway",
  "/logos/modalmais.png": "Modalmais",
  "/logos/n26.png": "N26",
  "/logos/neon.png": "Neon",
  "/logos/next.png": "Next",
  "/logos/nomad.png": "Nomad",
  "/logos/nu-invest.png": "NuInvest",
  "/logos/nubank-ultravioleta.png": "Nubank Ultravioleta",
  "/logos/nubank.pj.png": "Nubank PJ",
  "/logos/nubank.png": "Nubank",
  "/logos/nubank_chroma.png": "Nubank Chroma",
  "/logos/nuconta.png": "NuConta",
  "/logos/original.png": "Original",
  "/logos/pag.png": "Pag!",
  "/logos/pagar-me.png": "Pagar.me",
  "/logos/pagbank.png": "PagBank",
  "/logos/pagseguro.png": "PagSeguro",
  "/logos/pan.png": "PAN",
  "/logos/pao-acucar.png": "Pao de Acucar",
  "/logos/paypal.png": "PayPal",
  "/logos/petrobras.png": "Petrobras",
  "/logos/picpay.png": "PicPay",
  "/logos/pix.png": "Pix",
  "/logos/pluxxe.png": "Pluxee",
  "/logos/portoseguro.png": "Porto Seguro",
  "/logos/rappi-bank.png": "RappiBank",
  "/logos/recargapay.png": "RecargaPay",
  "/logos/renner.png": "Renner",
  "/logos/revolut.png": "Revolut",
  "/logos/riachuelo.png": "Riachuelo",
  "/logos/rico.png": "Rico",
  "/logos/safra.png": "Safra",
  "/logos/samsung.png": "Samsung",
  "/logos/santander-private.png": "Santander Private",
  "/logos/santander.png": "Santander",
  "/logos/sem-parar.png": "Sem Parar",
  "/logos/serasa-consumidor.png": "Serasa Consumidor",
  "/logos/shopee.png": "Shopee",
  "/logos/shoptime.png": "Shoptime",
  "/logos/sicoob.png": "Sicoob",
  "/logos/sicredi.png": "Sicredi",
  "/logos/sodexo.png": "Sodexo",
  "/logos/sofisadireto.png": "Sofisa Direto",
  "/logos/stone.png": "Stone",
  "/logos/tesourodireto.png": "Tesouro Direto",
  "/logos/tesouronacional.png": "Tesouro Nacional",
  "/logos/ton.png": "Ton",
  "/logos/toroinvestimentos.png": "Toro Investimentos",
  "/logos/trigg.png": "Trigg",
  "/logos/tudoazul.png": "TudoAzul",
  "/logos/uber.drive.png": "Uber Drive",
  "/logos/unicred.png": "Unicred",
  "/logos/unimed.seguros.png": "Unimed Seguros",
  "/logos/up.brasil.png": "Up Brasil",
  "/logos/viacredi.png": "Viacredi",
  "/logos/visa.png": "Visa",
  "/logos/votorantim.png": "Votorantim",
  "/logos/vr.png": "VR",
  "/logos/vuon.png": "Vuon",
  "/logos/wise.png": "Wise",
  "/logos/xp.png": "XP",
};

const featuredLogoSources = new Set([
  "/logos/nubank.png",
  "/logos/itau.png",
  "/logos/intermedium.png",
  "/logos/bradesco.png",
  "/logos/caixa.png",
  "/logos/santander.png",
  "/logos/c6bank.png",
  "/logos/picpay.png",
  "/logos/mercadopago.png",
  "/logos/xp.png",
]);

export type LogoCatalogItem = {
  src: string;
  label: string;
  featured: boolean;
};

export const logoCatalog: readonly LogoCatalogItem[] = Object.entries(logoLabels).map(
  ([src, label]) => ({ src, label, featured: featuredLogoSources.has(src) }),
);

export function getLogoLabel(src?: string | null) {
  if (!src) return "";
  if (logoLabels[src]) return logoLabels[src];

  const filename =
    src
      .split("/")
      .at(-1)
      ?.replace(/\.[^.]+$/, "") ?? "";
  return filename.replace(/[._-]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}
